name = "aep-control-plane"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "aep-db"
database_id = "REPLACE_ME"
migrations_dir = "../../infra/cloudflare/d1/migrations"

[[durable_objects.bindings]]
name = "WORKFLOW_COORDINATOR"
class_name = "WorkflowCoordinatorDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WorkflowCoordinatorDO"]

[vars]
APP_ENV = "dev"
SERVICE_NAME = "control-plane"

[env.staging]
name = "aep-control-plane-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "aep-staging"
database_id = "e09731a1-d37c-4833-8b79-e462643e2c36"
migrations_dir = "../../infra/cloudflare/d1/migrations"

[[env.staging.durable_objects.bindings]]
name = "WORKFLOW_COORDINATOR"
class_name = "WorkflowCoordinatorDO"

[env.staging.vars]
APP_ENV = "staging"
SERVICE_NAME = "control-plane"

[env.production]
name = "aep-control-plane-production"

[env.production.vars]
APP_ENV = "production"
SERVICE_NAME = "control-plane"