/* eslint-disable no-console */

import { handleOperatorAgentUnavailableSkip } from "../lib/operator-agent-skip";
import { resolveServiceBaseUrl } from "../lib/service-map";

export {};

type EscalationEntry = {
  escalationId: string;
  timestamp: string;
  severity: string;
  state: string;
  reason: string;
  affectedEmployeeIds: string[];
  message: string;
  acknowledgedAt?: string;
  acknowledgedBy?: string;
  resolvedAt?: string;
  resolvedBy?: string;
  resolutionNote?: string;
};

type EscalationsResponse = {
  ok: true;
  count: number;
  entries: EscalationEntry[];
};

type AcknowledgeResponse = {
  ok: true;
  escalation: EscalationEntry;
};

type ResolveResponse = {
  ok: true;
  escalation: EscalationEntry;
};

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required env var: ${name}`);
  }
  return value;
}

async function readJson<T>(response: Response): Promise<T> {
  const body = await response.text();
  if (!response.ok) {
    throw new Error(`Request failed: ${response.status} ${body}`);
  }
  return JSON.parse(body) as T;
}

async function main(): Promise<void> {
  const agentBaseUrl = resolveServiceBaseUrl({
    envVar: "OPERATOR_AGENT_BASE_URL",
    serviceName: "operator-agent",
  });

  // Step 1: find an open escalation to use as test subject
  const listResponse = await readJson<EscalationsResponse>(
    await fetch(`${agentBaseUrl}/agent/escalations?state=open&limit=5`)
  );

  if (!listResponse.ok) {
    throw new Error("/agent/escalations did not return ok=true");
  }

  let testEscalation = listResponse.entries[0];

  if (!testEscalation) {
    // No open escalations yet — run the manager to create some
    console.log("No open escalations found; running manager to generate some...");

    const managerResponse = await fetch(`${agentBaseUrl}/agent/run`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-aep-execution-source": "operator",
        "x-actor": "ci-lifecycle-check",
      },
      body: JSON.stringify({
        departmentId: "aep-infra-ops",
        employeeId: "emp_infra_ops_manager_01",
        roleId: "infra-ops-manager",
        trigger: "manual",
        targetEmployeeIdsOverride: [
          "emp_timeout_recovery_01",
          "emp_retry_supervisor_01",
        ],
      }),
    });

    if (!managerResponse.ok) {
      throw new Error(`Manager run failed: ${managerResponse.status}`);
    }

    const refetch = await readJson<EscalationsResponse>(
      await fetch(`${agentBaseUrl}/agent/escalations?state=open&limit=5`)
    );

    testEscalation = refetch.entries[0];

    if (!testEscalation) {
      console.log(
        "escalation-lifecycle-check: no escalations generated by manager in this run; skipping lifecycle transition assertions"
      );
      console.log("escalation-lifecycle-check passed (no open escalations to transition)");
      return;
    }
  }

  const id = testEscalation.escalationId;

  if (testEscalation.state !== "open") {
    throw new Error(
      `Expected escalation to start as open, got: ${testEscalation.state}`
    );
  }

  console.log("Found open escalation", { escalationId: id, reason: testEscalation.reason });

  // Step 2: acknowledge the escalation
  const ackResponse = await readJson<AcknowledgeResponse>(
    await fetch(`${agentBaseUrl}/agent/escalations/acknowledge?id=${encodeURIComponent(id)}`, {
      method: "POST",
      headers: { "x-actor": "ci-lifecycle-check" },
    })
  );

  if (!ackResponse.ok) {
    throw new Error("Acknowledge response did not return ok=true");
  }

  if (ackResponse.escalation.state !== "acknowledged") {
    throw new Error(
      `Expected state=acknowledged after acknowledge, got: ${ackResponse.escalation.state}`
    );
  }

  if (!ackResponse.escalation.acknowledgedAt) {
    throw new Error("Expected acknowledgedAt to be set after acknowledge");
  }

  if (ackResponse.escalation.acknowledgedBy !== "ci-lifecycle-check") {
    throw new Error(
      `Expected acknowledgedBy=ci-lifecycle-check, got: ${ackResponse.escalation.acknowledgedBy}`
    );
  }

  console.log("Verified open → acknowledged transition", {
    escalationId: id,
    acknowledgedAt: ackResponse.escalation.acknowledgedAt,
    acknowledgedBy: ackResponse.escalation.acknowledgedBy,
  });

  // Step 3: verify invalid backward transition is rejected
  const invalidAckResponse = await fetch(
    `${agentBaseUrl}/agent/escalations/acknowledge?id=${encodeURIComponent(id)}`,
    {
      method: "POST",
      headers: { "x-actor": "ci-lifecycle-check" },
    }
  );

  if (invalidAckResponse.ok) {
    throw new Error(
      "Expected re-acknowledging an already-acknowledged escalation to fail (invalid transition)"
    );
  }

  if (invalidAckResponse.status !== 400) {
    throw new Error(
      `Expected HTTP 400 for invalid transition, got: ${invalidAckResponse.status}`
    );
  }

  console.log("Verified invalid backward transition rejected (acknowledged → acknowledged = 400)");

  // Step 4: resolve the escalation
  const resolveResponse = await readJson<ResolveResponse>(
    await fetch(`${agentBaseUrl}/agent/escalations/resolve`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-actor": "ci-lifecycle-check",
      },
      body: JSON.stringify({
        id,
        note: "Resolved during CI lifecycle check",
      }),
    })
  );

  if (!resolveResponse.ok) {
    throw new Error("Resolve response did not return ok=true");
  }

  if (resolveResponse.escalation.state !== "resolved") {
    throw new Error(
      `Expected state=resolved after resolve, got: ${resolveResponse.escalation.state}`
    );
  }

  if (!resolveResponse.escalation.resolvedAt) {
    throw new Error("Expected resolvedAt to be set after resolve");
  }

  if (resolveResponse.escalation.resolutionNote !== "Resolved during CI lifecycle check") {
    throw new Error(
      `Unexpected resolutionNote: ${resolveResponse.escalation.resolutionNote}`
    );
  }

  console.log("Verified acknowledged → resolved transition", {
    escalationId: id,
    resolvedAt: resolveResponse.escalation.resolvedAt,
    resolutionNote: resolveResponse.escalation.resolutionNote,
  });

  // Step 5: verify open-only filter now excludes this escalation
  const openOnly = await readJson<EscalationsResponse>(
    await fetch(`${agentBaseUrl}/agent/escalations?state=open&limit=100`)
  );

  const stillOpen = openOnly.entries.find((e) => e.escalationId === id);
  if (stillOpen) {
    throw new Error(
      `Resolved escalation ${id} still appears in state=open filter`
    );
  }

  console.log("Verified resolved escalation excluded from state=open filter");

  // Step 6: verify resolved-only filter includes this escalation
  const resolvedOnly = await readJson<EscalationsResponse>(
    await fetch(`${agentBaseUrl}/agent/escalations?state=resolved&limit=100`)
  );

  const isResolved = resolvedOnly.entries.find((e) => e.escalationId === id);
  if (!isResolved) {
    throw new Error(
      `Resolved escalation ${id} not found in state=resolved filter`
    );
  }

  console.log("escalation-lifecycle-check passed", {
    escalationId: id,
    finalState: isResolved.state,
    stateTransitions: ["open", "acknowledged", "resolved"],
  });
}

main().catch((error) => {
  if (handleOperatorAgentUnavailableSkip("escalation-lifecycle-check", error)) {
    process.exit(0);
  }

  console.error("escalation-lifecycle-check failed");
  console.error(error);
  process.exit(1);
});
