export const EMPLOYEE_TIMEOUT_RECOVERY_ID = "op001";
export const EMPLOYEE_RETRY_SUPERVISOR_ID = "op002";
export const EMPLOYEE_INFRA_OPS_MANAGER_ID = "mg001";
export const EMPLOYEE_PRODUCT_MANAGER_ID = "pm001";
export const EMPLOYEE_PRODUCT_MANAGER_WEB_ID = "pm002";
export const EMPLOYEE_FRONTEND_ENGINEER_ID = "dv001";
export const EMPLOYEE_VALIDATION_PM_ID = "pm003";
export const EMPLOYEE_VALIDATION_ENGINEER_ID = "qa001";
export const EMPLOYEE_RELIABILITY_ENGINEER_ID = "qa002";

export const SEEDED_EMPLOYEE_IDS = [
  EMPLOYEE_TIMEOUT_RECOVERY_ID,
  EMPLOYEE_RETRY_SUPERVISOR_ID,
  EMPLOYEE_INFRA_OPS_MANAGER_ID,
  EMPLOYEE_PRODUCT_MANAGER_ID,
  EMPLOYEE_PRODUCT_MANAGER_WEB_ID,
  EMPLOYEE_FRONTEND_ENGINEER_ID,
  EMPLOYEE_VALIDATION_PM_ID,
  EMPLOYEE_VALIDATION_ENGINEER_ID,
  EMPLOYEE_RELIABILITY_ENGINEER_ID,
] as const;